// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ysQBgnsEf4QkGkFnDye1Ez8CrtyMXrU',
    appId: '1:908039459056:web:cec773cd49e226e5693235',
    messagingSenderId: '908039459056',
    projectId: 'smartirrigation-c6633',
    authDomain: 'smartirrigation-c6633.firebaseapp.com',
    databaseURL: 'https://smartirrigation-c6633-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartirrigation-c6633.appspot.com',
    measurementId: 'G-W0YL3TZR42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfU1JAgpFbjC1mx_uMO4MeX0kapBX7Qew',
    appId: '1:908039459056:android:5c97d088dd4c9d5c693235',
    messagingSenderId: '908039459056',
    projectId: 'smartirrigation-c6633',
    databaseURL: 'https://smartirrigation-c6633-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartirrigation-c6633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNV24mYfCrnsWeXK6ZTkJNTO2VnwAjK_0',
    appId: '1:908039459056:ios:16b5aec9371fc26a693235',
    messagingSenderId: '908039459056',
    projectId: 'smartirrigation-c6633',
    databaseURL: 'https://smartirrigation-c6633-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartirrigation-c6633.appspot.com',
    iosBundleId: 'com.example.smartirrigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNV24mYfCrnsWeXK6ZTkJNTO2VnwAjK_0',
    appId: '1:908039459056:ios:8852de42da4435be693235',
    messagingSenderId: '908039459056',
    projectId: 'smartirrigation-c6633',
    databaseURL: 'https://smartirrigation-c6633-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartirrigation-c6633.appspot.com',
    iosBundleId: 'com.example.smartirrigation.RunnerTests',
  );
}
